#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jun 17 02:17:53 CEST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim sys_tb_behav -key {Behavioral:sim_1:Functional:sys_tb} -tclbatch sys_tb.tcl -view /home/cesare/Uni/Progetto-ASDI-2025/8_prova_esame/Project/sys_tb_behav.wcfg -log simulate.log"
xsim sys_tb_behav -key {Behavioral:sim_1:Functional:sys_tb} -tclbatch sys_tb.tcl -view /home/cesare/Uni/Progetto-ASDI-2025/8_prova_esame/Project/sys_tb_behav.wcfg -log simulate.log

